[project]
name = "customer-360-intelligence-platform-end-to-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker==40.39.0",
    "numpy==2.4.6",
    "pandas==3.0.5",
    "python-dateutil==2.9.0.post0",
    "six==1.17.0",
    "tzdata==2026.4",
]
